apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ecommerce=praveen22233/ecommerce-app
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/Praveenchoudary/E-Commerce-Application-k8s-deploy.git
    targetRevision: main
    path: k8s-deployment

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
